### ISSUE TITLE
CodePush Release (ReactNative) leaves development flag set

### ISSUE THREAD

**Issue by mdshaner** [Microsoft/vscode-appcenter#122]
When using the CodePush release to deployment on a react-native project, it appears that it is creating the bundle with the development flag set. I ended up seeing the Yellow Box warnings.

**Comment by max-mironov** [comment]
Hey @mdshaner, than you so much for pointing this out!
Indeed this option is not defined in current implementation, so I've moved it to extension settings and it is `true` by default (as this is default option for rn bundler when this option is not set).

Please see PR [here](https://github.com/Microsoft/vscode-appcenter/pull/123). If you have no objections we will merge this and release new version in the nearest days.

We really appreciate your feedback and if you have any other ideas or see any issues - we are all ears.

**Comment by mdshaner** [comment]
That would be great. Thank you!

**Comment by max-mironov** [comment]
Thanks!
Just released [new version](https://github.com/Microsoft/vscode-appcenter/releases/tag/0.1.10) with fix.
Closing this one.
