### ISSUE TITLE
[info] profile not found

### ISSUE THREAD

**Issue by jwargo** [Microsoft/vscode-appcenter#124]
Ran into a problem where my Visual Studio Code instance hangs whenever I load it, then eventually gives me an error (info message). I reported it to the Visual Studio Code team, but once I deleted the App Center extension, the problem went away. So, I'm moving the issue here. 

Here's the original issue: https://github.com/Microsoft/vscode/issues/62280

**Comment by alex-oreshko** [comment]
Hi, @jonwargo, thanks for posting and sorry for confusion!

This message is shown if there is no existent profile file on your machine (we used this file to store information about logged in user thus it will be not required to login every time to App Center when you reopen VSCode).
Most often it means that you just need to login to our extension using status bar button.
Could you please try to log in to the extension and let us know if it helps?

Also what do you think, may be we should change this message to something more clear?
For example: “[VSCode AppCenter]: Profile was not found. Please try to log in to the App Center VSCode Extension.“?

**Comment by jwargo** [comment]
Thanks, I'll try it. Yes, you should identify the extension in the message. I'd do this: 

`[VSCode AppCenter]: Profile not found. Login to the App Center via the Visual Studio Code Extension to create the profile`

or something like that.

**Comment by jwargo** [comment]
@alex-oreshko actually, we're not allowed to use VSCode as a public name, and it's running in Visual Studio Code, so that's assumed, so how about this: 

[AppCenter]: Profile not found. Login to the App Center via the extension to create the profile

**Comment by alex-oreshko** [comment]
Thanks @jwargo, updated the log messages to have a clue about the source of it. This will be released in new version of the extension.
